### PR TITLE
Removed useless commas

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by quanglam2807** [comment]
@UnSimpleGeek Thanks a lot for the PR. Actually, those commas are there because of this ESLint rule: https://eslint.org/docs/rules/comma-dangle

**Comment by ghost** [comment]
@quanglam2807 Thanks for your answer, I removed it because of an error message while doing `npm start`.

Here is a Pastebin of the error : https://pastebin.com/TFuA2YUQ

Node version : 4.2.6
npm version : 3.5.2

**Comment by quanglam2807** [comment]
@UnSimpleGeek I should be fixed with https://github.com/webcatalog/electron-widevinecdm/releases/tag/v3.2.1

I recommend you to upgrade to Node.js 6+

**Comment by ghost** [comment]
@quanglam2807 Thanks a lot, keep up the good work !

**Pull request closed without merging**
